// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type TimeRecord struct {
	ID        uuid.UUID
	StartTime time.Time
	StopTime  sql.NullTime
	Duration  sql.NullInt64
	UserID    uuid.UUID
}

type User struct {
	ID       uuid.UUID
	Username string
	ApiKey   string
}
